name: Refresh NASA Data

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:        # Allows manual triggering

jobs:
  fetch_and_insert:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Ensure this matches your local Python version

      # Step 4: Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: powershell

      # Step 4.1: List ODBC drivers for debugging
      - name: List ODBC Drivers
        run: |
          python -c "import pyodbc; print('Available ODBC Drivers:', pyodbc.drivers())"
        shell: powershell

      # Step 5: Run the Python script
      - name: Run Script
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          DB_DRIVER: ${{ secrets.DB_DRIVER }}  # Ensure this matches the installed driver
          DB_SERVER: ${{ secrets.DB_SERVER }}  # Preferably use IP address
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python fetch_and_insert_nasa_data.py
        shell: powershell
