name: Refresh NASA Data

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:        # Allows manual triggering

jobs:
  fetch_and_insert:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Ensure this matches your local Python version

      # Step 3: Install Microsoft ODBC Driver for SQL Server without Chocolatey
      - name: Install Microsoft ODBC Driver for SQL Server
        run: |
          # Define the URL for the ODBC Driver 18 MSI installer
          $msiUrl = 'https://go.microsoft.com/fwlink/?linkid=2280794'  # Update this URL if needed
          
          # Define the path where the MSI will be downloaded
          $msiPath = "$env:TEMP\msodbcsql18.msi"

          Write-Host "Downloading Microsoft ODBC Driver 18 for SQL Server from $msiUrl"
          
          # Download the MSI installer
          Invoke-WebRequest -Uri $msiUrl -OutFile $msiPath

          Write-Host "Installing Microsoft ODBC Driver 18 for SQL Server"
          
          # Install the MSI silently
          Start-Process msiexec.exe -ArgumentList "/i `"$msiPath`" /quiet /norestart" -Wait

          Write-Host "Installation complete. Removing installer."

          # Remove the MSI installer after installation
          Remove-Item $msiPath -Force

          # Verify installation
          $driver = 'ODBC Driver 18 for SQL Server'
          $installed = Get-OdbcDriver | Where-Object { $_.Name -eq $driver }

          if ($installed) {
            Write-Host "$driver has been successfully installed."
          } else {
            Write-Error "Failed to install $driver."
            exit 1
          }
        shell: powershell

      # Step 4: Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: powershell

      # Step 5: Run the Python script
      - name: Run Script
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          DB_DRIVER: ${{ secrets.DB_DRIVER }}
          DB_SERVER: ${{ secrets.DB_SERVER }}  # Preferably use IP address
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python fetch_and_insert_nasa_data.py
        shell: powershell
