name: Refresh NASA Data

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:        # Allows manual triggering

jobs:
  fetch_and_insert:
    runs-on: windows-latest  # Change to self-hosted if using a self-hosted runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Ensure this matches your local Python version

      # Step 3: Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: powershell

      # Step 4: Test SQL Server Connectivity
      - name: Test SQL Server Connectivity
        shell: powershell
        run: |
          $server = "${{ secrets.DB_SERVER }}"
          $port = "${{ secrets.DB_PORT }}"
          $result = Test-NetConnection -ComputerName $server -Port $port
          $result | Format-List *
          if (-not $result.TcpTestSucceeded) {
            Write-Error "Cannot connect to SQL Server at $server on port $port."
          }

      # Step 5: Run the Python script
      - name: Run Script
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          DB_DRIVER: ${{ secrets.DB_DRIVER }}  # 'ODBC Driver 17 for SQL Server'
          DB_SERVER: ${{ secrets.DB_SERVER }}  # e.g., '192.168.1.100'
          DB_PORT: ${{ secrets.DB_PORT }}      # e.g., '1433'
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        shell: powershell
        run: |
          # Print available ODBC drivers for debugging
          python -c "import pyodbc; print('Available ODBC Drivers:', pyodbc.drivers())"
          
          # Run the main Python script
          python fetch_and_insert_nasa_data.py
