name: Refresh NASA Data

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:        # Allows manual triggering

jobs:
  fetch_and_insert:
    runs-on: windows-latest  # Specifies the use of a self-hosted runner named DAVID

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Verify Python and pip Installation
      - name: Verify Python and pip Installation
        shell: powershell
        run: |
          python --version
          pip --version

      # Step 3: Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: powershell

      # Step 4: Test SQL Server Connectivity
      - name: Test SQL Server Connectivity
        shell: powershell
        run: |
          $server = "${{ secrets.DB_SERVER }}"    # SQL Server IP address or hostname
          $port = "${{ secrets.DB_PORT }}"        # SQL Server port
          
          Write-Host "Testing connectivity to SQL Server at $server on port $port..."
          $result = Test-NetConnection -ComputerName $server -Port $port
          $result | Format-List *
          
          if (-not $result.TcpTestSucceeded) {
            Write-Error "Cannot connect to SQL Server at $server on port $port."
          } else {
            Write-Host "Successfully connected to SQL Server at $server on port $port."
          }

      # Step 5: Run the Python script
      - name: Run Script
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          DB_DRIVER: ${{ secrets.DB_DRIVER }}
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        shell: powershell
        run: |
          # Print available ODBC drivers for debugging
          python -c "import pyodbc; print('Available ODBC Drivers:', pyodbc.drivers())"
          
          # Run the main Python script
          python fetch_and_insert_nasa_data.py
